In [19]:
import numpy as np
x=list([int(i) for i in input().split()])
y=list([int(i) for i in input().split()])
x.sort()
y.sort()
x=np.array(x)
y=np.array(y)
x=x.reshape(1,5)
y=y.reshape(1,5)
z=np.concatenate((x,y),axis=1)
print(x)
print(y)
print(z)

1 2 3 4 5
6 7 8 9 0
[[1 2 3 4 5]]
[[0 6 7 8 9]]
[[1 2 3 4 5 0 6 7 8 9]]
